version: "3.6"
services:
    ###
    flask:
        build:
            context: ./flask
            args:
                flask_env: ${FLASK_ENV:-development}
        ports:
            - 5005:5000
            - 5001:5001
        networks:
            - backend
        volumes:
            - ./flask:/app/flask
        environment:
            PYTHONUNBUFFERED: 1
            MYSQL_HOST: db
            MYSQL_USER: root
            MYSQL_PASSWORD: dropapp_root
            MYSQL_DB: dropapp_dev
            MYSQL_PORT: 3306
            FLASK_APP: main.py
    ###
    frontend:
        build:
            context: ./frontend
        environment:
            NODE_ENV: development
            REACT_APP_REDIRECT: http://localhost:3000
            REACT_APP_LOGOUT_URL: http://localhost:3000
            REACT_APP_GRAPHQL_SERVER: http://localhost:5005/graphql
        ports:
            - 3000:3000
        stdin_open: true
        volumes:
            - ./frontend:/app/frontend
            - ./flask:/app/flask
            - ./frontend/package.json:/app/frontend/package.json
            - ./frontend/yarn.lock:/app/frontend/yarn.lock
            - /app/frontend/node_modules
    ###
    db:
        image: mysql/mysql-server:8.0
        command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
        environment:
            MYSQL_ROOT_PASSWORD: dropapp_root
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: dropapp_dev
        ports:
            - 32000:3306
        networks:
            - backend
###
networks:
    backend:
        driver: bridge
