version: 2.1

jobs:
  # checkout
  checkout-to-workspace:
    docker:
      - image: cimg/python:3.8.12-node
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
  # flask
  build-flask:
    docker:
      - image: cimg/python:3.8.12
    working_directory: ~/flask
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
  # react
  build-react:
    docker:
      - image: cimg/python:3.8.12-node
    working_directory: ~/frontend
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: Install Yarn Packages
          command: yarn install --immutable
      - run:
          name: Build React App
          command: |
            yarn build
      - persist_to_workspace:
          root: ~/
          paths:
            - frontend/build
  # deploy

workflows:
  # build workflow
  build_workflow:
    jobs:
      - checkout-to-workspace
      - build-flask:
          requires:
            - checkout-to-workspace
          filters:
            branches:
              only: master
      - build-react:
          requires:
            - checkout-to-workspace
          filters:
            branches:
              only: master