version: 2.1

jobs:
  # flask
  build-flask:
    docker:
      - image: cimg/python:3.8.12
    working_directory: ~/flask
    steps:
      - run:
          name: create the python virtual environment and install non-cached dependencies
          command: |
            pyenv root
            python --version
            pyenv virtualenvs
            pyenv virtualenv --force env
            source $(pyenv root)/versions/3.8.12/envs/env/bin/activate
            pip install -e . -r requirements.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - flask/*
            - .pyenv/versions/3.8.12/envs
  # react
  build-react:
    docker:
      - image: cimg/python:3.8.12-node
    working_directory: ~/frontend
    steps:
      - run:
          name: Install Yarn Packages
          command: yarn install --immutable
      - run:
          name: Build React App
          command: |
            yarn build
      - persist_to_workspace:
          root: ~/
          paths:
            - frontend/build
  # deploy

workflows:
  # build workflow
  build_workflow:
    jobs:
      - build-flask:
          filters:
            branches:
              only: master
      - build-react:
          filters:
            branches:
              only: master