runtime: python310 # or another supported version
env: standard
entrypoint: gunicorn -b :$PORT
instance_class: F1
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto